name: Docker image CI for CHCR

on:
  push

jobs:
  build_and_publish:
    runs: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build and push the images
        run: |
          docker login --username Andresmup --password ${{ secrets.GH_TOKEN}} ghcr.io
          docker build . -t ghcr.io/andresmup/lambda-s3-alb-container:latest
          cd docker push  ghcr.io/andresmup/lambda-s3-alb-container:latest